using System;
using System.Collections.Generic;
namespace DSMGenNHibernate.EN.DSM
{
public class UsuarioEN_OID
{
private string email;
public virtual string Email {
        get { return email; } set { email = value;  }
}




private int id;
public virtual int Id {
        get { return id; } set { id = value;  }
}






public UsuarioEN_OID()
{
}
public UsuarioEN_OID(string email, int id)
{
        this.email = email;
        this.id = id;
}

public override bool Equals (object obj)
{
        if (obj == null)
                return false;
        UsuarioEN_OID t = obj as UsuarioEN_OID;
        if (t == null)
                return false;


        if (this.email == t.Email && this.id == t.Id)

                return true;
        else
                return false;
}

public override int GetHashCode ()
{
        int hash = 13;

        // Su tipo es String
        hash = hash +
               (null == email                                                    ? 0 : this.email.GetHashCode ());
        // Su tipo es Autogenerated
        hash = hash +
               (0 == id                                                 ? 0 : this.id.GetHashCode ());
        return hash;
}
}
}
